### ISSUE TITLE
Dotnet Ubuntu ?

### ISSUE THREAD

**Issue by bsk193** [parkervcp/yolks#140]
Will it work if you just get the dockerfile from dotnet steamcmd and change target to ubuntu ? i cant create the package on my fork :( thanks

**Comment by QuintenQVD0** [comment]
> Will it work if you just get the dockerfile from dotnet steamcmd and change target to ubuntu ? i cant create the package on my fork :( thanks

No. There should be no need to use ubunru in any way

**Comment by QuintenQVD0** [comment]
There package names are difrend. And there dotnet repo also
