### ISSUE TITLE
Package Request: jq

### ISSUE THREAD

**Issue by Blob-Senpai** [parkervcp/yolks#142]
Can we get support to parse certain files such as json and xml in the games containers? One such library I would recommend is ‘jq’.

**Comment by QuintenQVD0** [comment]
> Can we get support to parse certain files such as json and xml in the games containers? One such library I would recommend is ‘jq’.

that is where the configuration parser is for on the panel. There should be no need for JQ in the game container

**Comment by QuintenQVD0** [comment]
if you need jq in a specific image feel free to PR it. The automatically setting some values in config files can be done with the panel configuration parser

**Comment by Blob-Senpai** [comment]
The need for parsing would be an scripts to bring support to automatically update game servers to detect an update and start the process of restarting the container.

Is there another way of doing this in bash or a built in way I missed? Right now I see that the panel “auto update” is used only to check for updates on start of the container.

**Comment by lilkingjr1** [comment]
@Blob-Senpai To be fair to your request, what yolk are you looking to add jq to? Because if it’s added, you’d probably want to do even more logic within the yolk to use it, so I’m curious what you’re looking to do.

**Comment by Blob-Senpai** [comment]
> @Blob-Senpai To be fair to your request, what yolk are you looking to add jq to? Because if it’s added, you’d probably want to do even more logic within the yolk to use it, so I’m curious what you’re looking to do.

All I want to do is detected if a workshop mod or if a game itself updated through the steamcmd. I would like to be able to parse the response back from it. Currently I can just do the public branch and not do the workshop mobs because that is just more work than I want to manually do.
