### ISSUE TITLE
Games:source rcon not accessible

### ISSUE THREAD

**Issue by Blob-Senpai** [parkervcp/yolks#143]
When attempting to reference the rcon executable that should be in /usr/local/bin, it does not exist. Also doing an ‘ls’ in this directory returns an empty directory.

**Comment by QuintenQVD0** [comment]
it is definitly in there and works

![afbeelding](https://user-images.githubusercontent.com/67589015/225980524-1ec6ed10-4997-4201-88b1-6f1023e7516d.png)
![afbeelding](https://user-images.githubusercontent.com/67589015/225980673-9d8d5fd0-ee62-4501-b2c3-8c5127df18fd.png)

**Comment by Blob-Senpai** [comment]
I’ll dump my cache and check. Thanks.
