### ISSUE TITLE
Add new NodeJS

### ISSUE THREAD

**Issue by tencreator** [parkervcp/yolks#146]
Could you maybe add a docker container for NodeJS 16.13.2

**Comment by gOOvER** [comment]
> Could you maybe add a rocker container for NodeJS 16.13.2

cointainers will be rebuilded once a week. You have to wait, if the nodejs 16 image is not up2date

**Comment by tencreator** [comment]
Ok, I needed it because one of the servers I bought uses it.

**Comment by QuintenQVD0** [comment]
it uses the latest sub version of 16, if you need any other contact the bot dev or make your own

**Comment by tencreator** [comment]
Ok, I did try making my own but it didn’t work when I tried uploading it to GitHub, the repo didn’t register

**Comment by QuintenQVD0** [comment]
> Ok, I did try making my own but it didn’t work when I tried uploading it to GitHub, the repo didn’t register

You can always local build it
Google how to build your own docker images localy

**Comment by tencreator** [comment]
Ok, I will try that thank you!
