### ISSUE TITLE
ghcr.io/parkervcp/games:source not found

### ISSUE THREAD

**Issue by zestian56** [parkervcp/yolks#154]
When creating a project zomboid seed this error araises

![image](https://github.com/parkervcp/yolks/assets/29008143/f9363240-fbf7-4b54-aa4b-01c4ecac4dd9)

**Comment by Software-Noob** [comment]
Docker pull the image on your machine to find out more - something is preventing you from being able to pull it.

**Comment by QuintenQVD0** [comment]
ghcr.io/parkervcp/games:source is definitly there. So you have a dns issue or girhub registrar is offline

**Comment by parkervcp** [comment]
This can also be an issue if you are running on ARM as the images are only built for amd64.

**Comment by zestian56** [comment]
> This can also be an issue if you are running on ARM as the images are only built for amd64.

You are right, im am running on arm, theres no way to use this yolk, or another one for project zomboid?
