### ISSUE TITLE
Java entrypoint.sh permissions bug

### ISSUE THREAD

**Issue by kev626** [parkervcp/yolks#173]
When starting Java containers (Java 17 tested) on the latest  build (released <1 hour ago) the following error occurs indicating a permissions issue of some kind with the entrypoint file:

```
environment/docker: failed to start container: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": permission denied: unknown
```

**Comment by gOOvER** [comment]
are you on unraid?

pls Post output of

hostnamectl status

**Comment by kev626** [comment]
> are you on unraid?
> 
> pls Post output of
> 
> hostnamectl status

This is not an unraid system and this error occurs on any system that attempts to execute the latest build of the Java 17 egg (and likely all of the others as well).

```
root@DFW-04-5950x:~# hostnamectl status
   Static hostname: DFW-04-5950x
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: <snip>
           Boot ID: <snip>
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-20-amd64
      Architecture: x86-64
```

**Comment by kev626** [comment]
See:

```
root@pterotest:~# curl https://get.docker.com | bash
<snip>

root@pterotest:~# docker run -it --rm ghcr.io/parkervcp/yolks:java_17
Unable to find image 'ghcr.io/parkervcp/yolks:java_17' locally
java_17: Pulling from parkervcp/yolks
7007490126ef: Pull complete
56c7ccc62e5c: Pull complete
56fed29f45ad: Pull complete
33cb37dbba70: Pull complete
0ef4548c8825: Pull complete
a3c17b0d923c: Pull complete
4f4fb700ef54: Pull complete
ce0df5629fec: Pull complete
Digest: sha256:ac2a806d0890bab817c259fbddd81e0e1cb8e555db14fbbb8780e2a04e6590a9
Status: Downloaded newer image for ghcr.io/parkervcp/yolks:java_17
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": permission denied: unknown.
ERRO[0020] error waiting for container:
```

Replicated on a completely fresh Debian 11 system.

**Comment by Goldragon747** [comment]
Seems to be affecting me as well

**Comment by parkervcp** [comment]
Considering the entrypoint hasn't had to change in over a year and all the java docker files are 6 months old this is a strange turn of events.

**Comment by kev626** [comment]
> Considering the entrypoint hasn't had to change in over a year and all the java docker files are 6 months old this is a strange turn of events.

I'm not disagreeing with you. But like I said, run it yourself. On a freshly installed system this happens.

**Comment by parkervcp** [comment]
This isn't a permissions issue but a bug with the build

**Comment by gOOvER** [comment]
it IS. Had the same problems and Quinten dont add the permissions fix, i told him.

See:
https://github.com/gOOvER/own-pterodactyl-images/blob/0a8dcdcc05c62eac5e1c0e039b74e2d252aa77bc/steamcmd/debian/Dockerfile#L114

**Comment by parkervcp** [comment]
The issue I still have is that this worked before today's build. There is no reason it shouldn't work.

**Comment by gOOvER** [comment]
btw. i cant confirm the issue:
![Screenshot_2023-08-14-05-49-57-920_com.android.chrome-edit.jpg](https://github.com/parkervcp/yolks/assets/116325/6cf8bac1-9dd3-406a-bd06-4442258b58b5)

latest yolk

**Comment by kev626** [comment]
> btw. i cant confirm the issue: ![Screenshot_2023-08-14-05-49-57-920_com.android.chrome-edit.jpg](https://user-images.githubusercontent.com/116325/260353888-6cf8bac1-9dd3-406a-bd06-4442258b58b5.jpg)
> 
> latest yolk

You're using the wrong image. This affects the Java 17 image. Your screenshot/test is irrelevant. It can be replicated using the commands I showed above. This IS an issue.

**Comment by gOOvER** [comment]
> Seems to be affecting me as well

can you show me also the Output of:

hostnamectl status?

**Comment by gOOvER** [comment]
> You're using the wrong image. This affects the Java 17 image. Your screenshot/test is irrelevant. It can be replicated using the commands I showed above. This IS an issue.

you are right. i clicked the wrong Egg. sry, only online in my mobile.

i can confirm this Error and now WE are Back to Dannys fix and my post above

**Comment by ConsulHosting** [comment]
We have this problem aswell.
