### ISSUE TITLE
Valheim EntryPoint using exec prevents proper kill signal from being sent to the valheim server process.

### ISSUE THREAD

**Issue by dreamwraith** [parkervcp/yolks#199]
/parkervcp/yolks/blob/master/games/valheim/entrypoint.sh  utilizes an exec for running the server command, which prevents SIGINT from reaching the valheim server process directly. This server binary requires a SIGINT to gracefully shutdown, there is no "console" command for shutdown. Result is that server behaves like a hard crash on shutdown, not saving configuration files or triggering other "shutdown" processes.

**Comment by QuintenQVD0** [comment]
Not an issue on the image side, but in pterodactyl wings. use the image: ´quintenqvd/pterodactyl_tini:games_valheim` and set the stop cmd of the egg to `^C` it will send SIGINT

**Comment by dreamwraith** [comment]
> Not an issue on the image side, but in pterodactyl wings. use the image: ´quintenqvd/pterodactyl_tini:games_valheim`and set the stop cmd of the egg to`^C` it will send SIGINT

Pterodactyl has consistently closed issues related to this and pointed the finger at images/eggs :(.

Either way, thanks for publishing a workaround!
