### ISSUE TITLE
Factorio Yolk out of date

### ISSUE THREAD

**Issue by DarkTerrorWolf** [parkervcp/yolks#200]
The Yolk For Factorio Is now out of date and the auto updater keeps reverting whatever progress I make.
 All attempts to force an update through docker control have been unsuccessful and with no scripts or instructions on how to force a yolk update from the server or from client side.
 
 Help appreciated.

**Comment by parkervcp** [comment]
Yolk images auto update if there are changes. Can you get the output from the startup to show the issue?

**Comment by DarkTerrorWolf** [comment]
![image](https://github.com/parkervcp/yolks/assets/56730822/5bb77b55-eb7a-42a2-b685-c9b0d176ea77)
![image](https://github.com/parkervcp/yolks/assets/56730822/629b8e7b-088c-4b90-8af6-da2c4b56c09d)

`container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
Digest: sha256:50ad729a4220782a5d483e93dfd5695f08aa4136e9d9461163d98c7163d87b7d 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ if [ ! -f "./saves/${SAVE_NAME}.zip" ]; then ./bin/x64/factorio --create ./saves/${SAVE_NAME}.zip --map-gen-settings data/map-gen-settings.json --map-settings data/map-settings.json; fi; ./bin/x64/factorio --port ${SERVER_PORT} --server-settings data/server-settings.json --start-server saves/${SAVE_NAME}.zip
   0.000 2023-10-30 16:03:10; Factorio 1.1.91 (build 61680, linux64, headless)
   0.058 Operating system: Linux (Debian 11)
   0.058 Program arguments: "./bin/x64/factorio" "--port" "3001" "--server-settings" "data/server-settings.json" "--start-server" "saves/Default_Run_mk1.zip" 
   0.058 Config path: /home/container/config/config.ini
   0.058 Read data path: /home/container/data
   0.058 Write data path: /home/container [829965/937290MB]
   0.058 Binaries path: /home/container/bin
   0.074 System info: [CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 48 cores, RAM: 32017 MB]
   0.074 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
   0.074 Running in headless mode
   0.131 Loading mod core 0.0.0 (data.lua)
   0.174 Loading mod base 1.1.91 (data.lua)
   0.496 Loading mod base 1.1.91 (data-updates.lua)
   0.620 Checksum for core: 2152183905
   0.620 Checksum of base: 410454729
   0.933 Prototype list checksum: 3034860339
   0.983 Info PlayerData.cpp:76: Local player-data.json available, timestamp 1698706988
   0.983 Info PlayerData.cpp:83: Cloud player-data.json unavailable
   0.985 Factorio initialised
   0.986 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
   0.986 Info ServerMultiplayerManager.cpp:813: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
   0.986 Info ServerMultiplayerManager.cpp:813: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
   0.986 Loading map /home/container/saves/Default_Run_mk1.zip: 11097041 bytes.
   1.008 Loading level.dat: 37676087 bytes.
   1.021 Info Scenario.cpp:204: Map version 1.1.91-0
   2.899 Loading script.dat: 1182 bytes.
   2.903 Checksum for script /home/container/temp/currently-playing/control.lua: 3702463597
   2.909 Info UDPSocket.cpp:33: Opening socket at (IP ADDR:({0.0.0.0:3001}))
   2.909 Hosting game at IP ADDR:({0.0.0.0:3001})`

**Comment by parkervcp** [comment]
This would need to be an issue opened for my eggs repo here - <https://github.com/parkervcp/eggs/issues/new/choose>

**Comment by gOOvER** [comment]
> ![image](https://github.com/parkervcp/yolks/assets/56730822/5bb77b55-eb7a-42a2-b685-c9b0d176ea77)
> ![image](https://github.com/parkervcp/yolks/assets/56730822/629b8e7b-088c-4b90-8af6-da2c4b56c09d)
> 
> `container@pterodactyl~ Server marked as starting...
> [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
> Pulling from parkervcp/yolks 
> Status: Image is up to date for ghcr.io/parkervcp/yolks:debian 
> Digest: sha256:50ad729a4220782a5d483e93dfd5695f08aa4136e9d9461163d98c7163d87b7d 
> [Pterodactyl Daemon]: Finished pulling Docker container image
> :/home/container$ if [ ! -f "./saves/${SAVE_NAME}.zip" ]; then ./bin/x64/factorio --create ./saves/${SAVE_NAME}.zip --map-gen-settings data/map-gen-settings.json --map-settings data/map-settings.json; fi; ./bin/x64/factorio --port ${SERVER_PORT} --server-settings data/server-settings.json --start-server saves/${SAVE_NAME}.zip
>    0.000 2023-10-30 16:03:10; Factorio 1.1.91 (build 61680, linux64, headless)
>    0.058 Operating system: Linux (Debian 11)
>    0.058 Program arguments: "./bin/x64/factorio" "--port" "3001" "--server-settings" "data/server-settings.json" "--start-server" "saves/Default_Run_mk1.zip" 
>    0.058 Config path: /home/container/config/config.ini
>    0.058 Read data path: /home/container/data
>    0.058 Write data path: /home/container [829965/937290MB]
>    0.058 Binaries path: /home/container/bin
>    0.074 System info: [CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz, 48 cores, RAM: 32017 MB]
>    0.074 Environment: DISPLAY=<unset> WAYLAND_DISPLAY=<unset> DESKTOP_SESSION=<unset> XDG_SESSION_DESKTOP=<unset> XDG_CURRENT_DESKTOP=<unset> __GL_FSAA_MODE=<unset> __GL_LOG_MAX_ANISO=<unset> __GL_SYNC_TO_VBLANK=<unset> __GL_SORT_FBCONFIGS=<unset> __GL_YIELD=<unset>
>    0.074 Running in headless mode
>    0.131 Loading mod core 0.0.0 (data.lua)
>    0.174 Loading mod base 1.1.91 (data.lua)
>    0.496 Loading mod base 1.1.91 (data-updates.lua)
>    0.620 Checksum for core: 2152183905
>    0.620 Checksum of base: 410454729
>    0.933 Prototype list checksum: 3034860339
>    0.983 Info PlayerData.cpp:76: Local player-data.json available, timestamp 1698706988
>    0.983 Info PlayerData.cpp:83: Cloud player-data.json unavailable
>    0.985 Factorio initialised
>    0.986 Info ServerSynchronizer.cpp:29: nextHeartbeatSequenceNumber(0) initialized Synchronizer nextTickClosureTick(0).
>    0.986 Info ServerMultiplayerManager.cpp:813: updateTick(4294967295) changing state from(Ready) to(PreparedToHostGame)
>    0.986 Info ServerMultiplayerManager.cpp:813: updateTick(4294967295) changing state from(PreparedToHostGame) to(CreatingGame)
>    0.986 Loading map /home/container/saves/Default_Run_mk1.zip: 11097041 bytes.
>    1.008 Loading level.dat: 37676087 bytes.
>    1.021 Info Scenario.cpp:204: Map version 1.1.91-0
>    2.899 Loading script.dat: 1182 bytes.
>    2.903 Checksum for script /home/container/temp/currently-playing/control.lua: 3702463597
>    2.909 Info UDPSocket.cpp:33: Opening socket at (IP ADDR:({0.0.0.0:3001}))
>    2.909 Hosting game at IP ADDR:({0.0.0.0:3001})`
>    
>    The server is calling that It is up to date when the updated version is 1.1.94 not 1.1.91. manual and forced updating of the server failed
> 

factorio have No Autoupdate. you must reinstall the server
