### ISSUE TITLE
Mumble not up to date

### ISSUE THREAD

**Issue by Tealk** [parkervcp/yolks#224]
The Mumble container is not up to date, when I start it via pterodactyl 1.4.0 is started but currently 1.4.287 would be and soon 1.5.x should be released.
https://www.mumble.info/blog/mumble-1.5.613-rc-2/

```
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from parkervcp/yolks 
Status: Image is up to date for ghcr.io/parkervcp/yolks:voice_mumble 
Digest: sha256:a1aae7383a567475d5bde4e5e2dafa837d937bf1e2ca4025fa79d4dd566c2ac3 
[Pterodactyl Daemon]: Finished pulling Docker container image
<W>2024-03-04 06:47:01.336 Murmur 1.4.0 (1.4.0) running on Linux: Alpine Linux v3.16 [x64]: Booting servers
```

**Comment by QuintenQVD0** [comment]
This is not up to us, if they update the alpine binary then the image will also update to the new version

**Comment by Tealk** [comment]
> if they update the alpine binary

who exactly? who can I bother with this? :P

**Comment by QuintenQVD0** [comment]
> > if they update the alpine binary
> 
> who exactly? who can I bother with this? :P

If they release not pre release 1.5 then it will auto update.

**Comment by Tealk** [comment]
I'm not talking about 1.5, but about 1.4, which is 1.4.0 on the server, but 1.4.287 has already been released, and that as a release and not as a prerelease or anything else.

**Comment by QuintenQVD0** [comment]
> I'm not talking about 1.5, but about 1.4, which is 1.4.0 on the server, but 1.4.287 has already been released, and that as a release and not as a prerelease or anything else.
> 
> I only mentioned that 1.5 will follow soon and that I would like to install it promptly and that certainly won't work if there isn't even the latest 1.4 update now.

The version in the image is 1.4.287-r10 even as it shows as 1.4.0

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/parkervcp/yolks/assets/67589015/9daf82c8-2528-42ec-a60b-70c1777e1343)

**Comment by QuintenQVD0** [comment]
I see the issue, we locked this image at alpine 3.16 so it stopped at 1.4.200 but it will still say on latest 1.4.0

**Comment by Tealk** [comment]
great, thank you then I'm looking forward to the update
