### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by Timo972** [parkervcp/yolks#228]
Hey guys, first of all thanks for your great work on all of these game server images.

I am interested in running games such as Valheim and Satisfactory on my Orange Pi 5 which is an arm board just like the raspberry pi. Since most of the game servers and images are only built for amd64, I am having trouble running these images on arm64.
That's why I'd like to introduce a [box86](https://github.com/ptitSeb/box86) image, which in combination with the box64 image could be used to run any amd64 binary inside an arm64 image.

As an example for the valheim image, box86 could be used to run the SteamCMD and download the required server files. The server binary itself could then be run using the box64 emulator.

Even though one might argue about the most likely degraded performance,
in my opinion being able to run these games on arm using emulators is better than simply not supporting the platform at all. 

Best regards

**Comment by QuintenQVD0** [comment]
Running box86 is and will be a pain as it needs multiple software compiled on the host. Look in to ly repo. It has some things for arm64 pterodactyl eggs with multiple emulators.  Native this is way to diffucult to officaly support.

**Comment by Timo972** [comment]
I didn't find your eggs in the first place, they're exactly what I am looking for! Thanks for your dedication
