### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KirovYuri** [parkervcp/yolks#232]
```
:/home/container$ ./omp-server
./omp-server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by QuintenQVD0** [comment]
Libssl1.1 is long EOL and not secure anymore. Tell the devs to update to libssl3 and update your egg.

**Comment by QuintenQVD0** [comment]
https://github.com/parkervcp/eggs/pull/2855

Please use this, if their plugin issues after then make a issue on the eggs repo, I have a hacky but working fix.

**Comment by VibeGAMESNL** [comment]
This is also causing issues for a big amount of CS2 plugins.
