### ISSUE TITLE
libssl.so.1.1 issues CS2

### ISSUE THREAD

**Issue by VibeGAMESNL** [parkervcp/yolks#236]
Much closed source csgo/cs2 plugins are having issues now libssl 1.1 is removed.

`Error reloading plugin: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by QuintenQVD0** [comment]
Complain to the devs. Libssl1.1 is eol and not supported anymore for 2 +years

**Comment by QuintenQVD0** [comment]
If I al allowed by the right persons. I add it back to the source and steamcmd debian one. But I can not promis anything. Its just so you all stop I'm tired of all this whining. 

This should not be fixt on our side.

**Comment by VibeGAMESNL** [comment]
I understand what you say but sometimes its just not possible to upgrade for various reasons if the dev is not responsive for example. Or maybe you can make some legacy version available that we could use.

**Comment by QuintenQVD0** [comment]
> I understand what you say but sometimes its just not possible to upgrade for various reasons if the dev is not responsive for example. It would be great if there is some workarround provided from your side.
> 
> Thanks for the consideration.

The os debian image, the source and steamcmd debian image will for now ship again with libssl1.1. 

We may in the futrue just make image for games that need libssl1.1

**Comment by Poggicek** [comment]
Please refer to https://github.com/Poggicek/mysql_mm/issues/11. Source2 games should run on debian 11 under steamrt environment, see https://github.com/1zc/CS2-Pterodactyl egg that properly does so.

Valve is trying to enforce the use of steamrt but it's still trying to be worked around causing these issues. Debian 11 still has 2 years left of support and even though libssl 1.1 is already beyond EOL it will still be patched by the debian maintainers. The developers cannot simply upgrade to libssl3 as it would completely break compatibility with debian 11 that is the only supported way to run source2 servers.

**Comment by QuintenQVD0** [comment]
The siper image did not update and can be used at all time. And in about 3 weeks debian security updates. As I toos for now if you want to run the sniper image based on steam ones. Feel free to. For the time been. Libssl1.1 will still be installed on the source and steamcmd debian image.

**Comment by Poggicek** [comment]
okay so, the cs2 egg uses the sniper image, which is correct. What egg is then vibegames using that it does not use that image and thus does not include libssl1.1? If that's the case (vibegames using wrong egg) then no action is needed as they have clearly mentioned it occurs only for cs2 which correctly uses the steamrt3

**Comment by QuintenQVD0** [comment]
![afbeelding](https://github.com/parkervcp/yolks/assets/67589015/4f806614-80bf-4c60-9de2-cb53b5416688)
THe sniper image was not touched, I am now adding back libssl1.1 to the source and steamcmd debian image.

then their now at least 4 images that have a version of libssl1.1

**Comment by Poggicek** [comment]
Yeah I'm not claiming that it was, the sniper image does indeed include libssl1.1 just fine, what I'm claiming is that vibegame is NOT using that sniper image for their cs2 servers for whatever reason, which is the whole reason for this to be an issue at all. I'm not exactly sure why the included "CSGO/CS2" instead of just CS2 but this issue is a result of an issue created inside my own repo which is exclusive only to CS2. So this once again loops back to vibegames improper setup or so.

**Comment by QuintenQVD0** [comment]
I am closing this, as this is some hoster issue. I thank you, @Poggicek, for your help and patient of clearing this with me.

For anyone else, there is from now libssl1.1 in the images I mentioned.
and Debian security support for 11 ends in  3 months yes the LTS team is still their.
