### ISSUE TITLE
GraalVM

### ISSUE THREAD

**Issue by raikasdev** [parkervcp/yolks#32]
I would personally need a GraalVM image (arm64) for one of my custom plugins running other languages.
https://github.com/graalvm/container/pkgs/container/graalvm-ce

**Comment by Software-Noob** [comment]
I've created 8 CE and 11/17 JDK versions for my own use. They can be found in [my repo here ](https://github.com/Software-Noob/pterodactyl-images#java-graalvm-amd64arm64)and could be PR'ed over.

**Comment by QuintenQVD0** [comment]
Just use Software-Noob. IF you want to pr them over that is fine.
