### ISSUE TITLE
apt update, upgrade, install should be single docker command

### ISSUE THREAD

**Issue by janisozaur** [parkervcp/yolks#35]
https://github.com/parkervcp/yolks/blob/8a4ef8387de35150c1b8f0ce9bf6c308d2e9f595/oses/debian/Dockerfile#L17-L23

`update && upgrade` and `install` are run in separate steps. This is bad practice due to docker storing partial image at time of `update` and when rebuilding it could start from `install` with stale packages.

See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run for more info

**Comment by Software-Noob** [comment]
We do not use caching for this to be an issue. Each new build is done from scratch

**Comment by lilkingjr1** [comment]
Definitely still good practice incase `apt update` or `apt upgrade` fails for some wild reason, but low priority if each build is done from scratch.

**Comment by Software-Noob** [comment]
We'll keep this in mind should we take advantage of workflow cache layering. However, at this point, we don't need it since images are not frequently rebuilt.
