### ISSUE TITLE
Source Image Discrepancy

### ISSUE THREAD

**Issue by lilkingjr1** [parkervcp/yolks#4]
Is the Source image supposed to be listed under `/games` or `/installers`? The image location is under `/games`, but the README has it's location and image link pointing to the `/installers` directory, which is invalid. I was going to submit a quick PR to fix it, but needed to know where you wanted it first.

**Comment by Software-Noob** [comment]
The `installers:source` and `games:source` are two separate images. `installers:source` was renamed to a generic `installers:debian`, but this change wasn't reflected in the readme. Thanks for the catch

**Comment by lilkingjr1** [comment]
@Software-Noob `games:source` is still missing from the games section of the readme then? Not a huge deal; just noticed.

**Comment by Software-Noob** [comment]
> @Software-Noob `games:source` is still missing from the games section of the readme then? Not a huge deal; just noticed.

Fixed in https://github.com/parkervcp/yolks/commit/b5c8d7ccc63df481499671588fab781974b3dbf6
