### ISSUE TITLE
Arma 3 command not found

### ISSUE THREAD

**Issue by sqall123** [parkervcp/yolks#51]
When server has started, its try to execute ifconfig showing the following message:
sh: 1: /sbin/ifconfig: not found

Needs install net-tools on image

**Comment by lilkingjr1** [comment]
The yolk (image) never calls /sbin/ifconfig. Not sure what image you are using with your egg, but your issue doesn't sound related to this image in particular.

**Comment by sqall123** [comment]
Im sure using this image and always get this error:
13:13:15 SteamAPI initialization failed. Steam features won't be accessible!
sh: 1: /sbin/ifconfig: not found
13:14:10 Dedicated host created.

Maybe SteamApi uses it or some related with Battleeye im not sure what exactly execute this.

**Comment by sqall123** [comment]
I found the command on both arma3 server binaries (arma3server_x64, arma3server).
/sbin/ifconfig | sed -n -e "s/.*HWaddr //p"
They try to get the mac address by HWaddr field but on "new" ifconfig command does not exist anymore.
Looks like is an old command from arma3server and can run without it.
Closing issue

**Comment by lilkingjr1** [comment]
> I found the command on both arma3 server binaries (arma3server_x64, arma3server).
/sbin/ifconfig | sed -n -e "s/.*HWaddr //p"
They try to get the mac address by HWaddr field but on "new" ifconfig command does not exist anymore.
Looks like is an old command from arma3server and can run without it.

Very interesting... I never knew this; thank you for the deep dive. If you don't mind me asking, how did you find out the compiled binary runs this code?

**Comment by sqall123** [comment]
> 

I try several commands for debug the binaries and finally get it with: strings arma3server_x64 | grep -i ifconfig
