### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by oqammx86** [parkervcp/yolks#55]
Yolk suggestion: Deno (https://deno.land/)

**Comment by WavingCatDevs** [comment]
I'm pretty sure you can modify this: https://github.com/parkervcp/yolks/blob/master/nodejs/18/Dockerfile

**Comment by parkervcp** [comment]
I already have a deno egg that doesn't need a custom image - https://github.com/parkervcp/eggs/blob/master/bots/discord/deno/egg-deno-generic.json

**Comment by oqammx86** [comment]
Oh ok
