### ISSUE TITLE
Box64 problem

### ISSUE THREAD

**Issue by SuperKali** [parkervcp/yolks#92]
Hello,

I'm experiencing this problem with your docker images:

![image](https://user-images.githubusercontent.com/19473898/200784728-89f20c5e-0051-498a-bdc5-0f5271c87b06.png)

You can fix it?

Thanks.

**Comment by QuintenQVD0** [comment]
> Hello,
> 
> I'm experiencing this problem with your docker images:
> 
> ![image](https://user-images.githubusercontent.com/19473898/200784728-89f20c5e-0051-498a-bdc5-0f5271c87b06.png)
> 
> You can fix it?
> 
> Thanks.

the box64 image does not support sinusbot. There is no offical egg for sinusbot with box64

**Comment by QuintenQVD0** [comment]
also not the sinusbot egg recently got a update to new image and that is build for arm64

**Comment by QuintenQVD0** [comment]
but you have to modify the egg because the pre releaes have a arm64 version but it is not in the egg

**Comment by SuperKali** [comment]
I didn't know they released a version for arm64

**Comment by SuperKali** [comment]
@QuintenQVD0 thanks now working :)
